# Generated by Django 3.1.6 on 2021-06-27 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_contact_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
