# Generated by Django 3.1.6 on 2021-03-23 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0007_category_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.userprofile'),
        ),
    ]
