# Generated by Django 3.1.6 on 2021-04-01 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0012_auto_20210329_0212'),
    ]

    operations = [
        migrations.AddField(
            model_name='followup',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_followup', to='leads.user'),
            preserve_default=False,
        ),
    ]
