# Generated by Django 3.1.6 on 2021-04-01 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0013_followup_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followup',
            name='user',
        ),
    ]
