# Generated by Django 3.1.6 on 2021-04-17 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0016_bills'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bills',
        ),
    ]
