# Generated by Django 3.1.6 on 2021-04-18 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0018_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_address',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_name',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_phone',
            field=models.CharField(max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_website',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
