# Generated by Django 3.1.6 on 2021-04-20 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0019_auto_20210418_0326'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Company',
        ),
    ]
