# Generated by Django 3.1.6 on 2021-04-29 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0022_auto_20210429_0121'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='user_profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_prof', to='leads.userprofile'),
            preserve_default=False,
        ),
    ]
