# Generated by Django 3.1.6 on 2021-04-29 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0023_useraccount_user_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='user',
        ),
    ]
