# Generated by Django 3.1.6 on 2021-04-29 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0024_remove_useraccount_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='user',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='user_account', to='leads.user'),
            preserve_default=False,
        ),
    ]
