# Generated by Django 3.1.6 on 2021-05-03 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0029_auto_20210503_0132'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Company',
        ),
    ]
