# Generated by Django 3.1.6 on 2021-05-05 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0030_delete_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='phone_number',
            field=models.CharField(max_length=13, unique=True),
        ),
    ]
