# Generated by Django 3.1.6 on 2021-05-05 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0031_auto_20210505_0127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='lead',
            name='phone_number',
            field=models.CharField(max_length=13),
        ),
    ]
