# Generated by Django 3.1.6 on 2021-05-17 17:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0032_auto_20210505_0145'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=40, null=True)),
                ('company_address', models.CharField(max_length=1000, null=True)),
                ('company_phone', models.CharField(max_length=13, null=True)),
                ('company_website', models.CharField(max_length=100, null=True)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='company_logo/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_company', to=settings.AUTH_USER_MODEL)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile_company', to='leads.userprofile')),
            ],
        ),
        migrations.DeleteModel(
            name='UserAccount',
        ),
    ]
