# Generated by Django 3.1.6 on 2021-05-18 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0033_auto_20210517_1756'),
        ('quotations', '0002_remove_invoice_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='leads.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lineitem',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='leads.company'),
            preserve_default=False,
        ),
    ]
