# Generated by Django 3.1.6 on 2021-05-18 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0034_auto_20210518_0051'),
        ('quotations', '0003_auto_20210518_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comp_name', to='leads.company'),
        ),
        migrations.AlterField(
            model_name='lineitem',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comp_name_li', to='leads.company'),
        ),
    ]
